version: '3.8'

services:
  postgresql:
    container_name: earnlab_postgresql
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=earnlab
      - POSTGRES_PASSWORD=earnlab
      - POSTGRES_DB=earnlab
    volumes:
      - earnlab_postgresql:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - earnlab_network
    ports:
      - "6543:5432"

  app:
    container_name: earnlab_backend
    image: earnlab_backend
    build: 
      context: .
      dockerfile: ./Dockerfile-dev
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - redis
    volumes:
      - earnlabapp_data:/usr/src/app
    networks:
      - earnlab_network

  redis:
    container_name: earnlab_redis
    image: redis:latest
    networks:
      - earnlab_network
    volumes:
      - earnlab_redis:/data

networks:
  earnlab_network:
    driver: bridge

volumes:
  earnlab_postgresql:
  earnlabapp_data:
  earnlab_redis: